# Generated by Django 5.2.1 on 2025-06-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
